### ISSUE TITLE
scroller组件不能即时更新inner的高度

### ISSUE THREAD

**Issue by wen911119** [weexteam/weex-vue-render#11]
loadmore事件需要对比inner和wrap的高度，但是这两个数值都是在render时候拿到的。如果scroller里面的内容是动态的，比如懒加载，那么render时候拿到的高度数值就不准确了。需要手动调用updateLayout()来更新，但是updateLayout这个api在文档里并没有看见，只有扒源码才能看见

**Comment by MrRaindrop** [comment]
内容变动以后 render 里会自动根据变动以后的 inner 和 wrap 高度做对比的，不需要手动调用 updateLayout，可以参见一下这个 [demo](http://dotwe.org/vue/967edb33f624c958fbf1388bacdbb926)
