### ISSUE TITLE
急！H5渲染时，为什么打开时，页面很多图标都不会显示

### ISSUE THREAD

**Issue by vebin** [weexteam/weex-vue-render#13]
H5渲染时，为什么打开时，页面很多图标都不会显示···
要有点击、或改变元素，就会再显示出来？
我H5端使用了vue-router ，router-view跳转使用了transition 动画过度··

**Comment by MrRaindrop** [comment]
在 http://dotwe.org/vue 上提供一个可以复现的 demo 我帮你看下

**Comment by MrRaindrop** [comment]
@vebin 推测可能的原因是 transition 过度不会触发页面的图片懒加载检测，你可以通过在适当的时机调用 `weex.utils.fireLazyload(el, ignoreVisibility)` 来触发图片懒加载检测，这行代码必须运行在 web 环境下，weex native 环境会报错，所以需要先判断环境.
