### ISSUE TITLE
px2rem 

### ISSUE THREAD

**Issue by BrightMi** [weexteam/weex-vue-render#14]
在style中不能从px到rem转换margin-bottom这种的样式
:style="{'margin-bottom':'40px'}"
version 1.0.20

**Comment by MrRaindrop** [comment]
目前仅支持了 camelCase 的样式名称，kebab-case 的支持已列入计划 https://github.com/weexteam/weex-vue-render/projects/1.

**Comment by MrRaindrop** [comment]
相关 issue: https://github.com/weexteam/weex-vue-precompiler/issues/2
已 fix: https://github.com/weexteam/weex-vue-precompiler/commit/d5303967eabcefee67ffb9dcc16c98285d0fa285
请升级 weex-vue-precompiler 到 v0.1.18 即可.
