### ISSUE TITLE
升级到1.x显示空白

### ISSUE THREAD

**Issue by Coder-Ethan** [weexteam/weex-vue-render#16]
vue组件使用weex compile --web方式打包为js bundle，在使用0.12.22可以正常显示
将weex-vue-render升级为最新版本时，页面显示空白！

entry.js代码如下：
`import foo from './src/HelloWorld.vue'`
`foo.el = "#root"`
`export default new Vue(foo)`

**Comment by wangzhenyu1260** [comment]
同问

**Comment by MrRaindrop** [comment]
1.x 版本和 0.12.x 版本对不同版本的编译方式编出来的包是互不兼容的，手动打包可以看下 https://github.com/weexteam/weex-vue-render#pack-your-vue-file-to-webbundlejs
