### ISSUE TITLE
在ios的safari上bfcache失效（MessageChannel引起）

### ISSUE THREAD

**Issue by wen911119** [weexteam/weex-vue-render#17]
问题复现：
1.打开下面dotWe链接：
http://dotwe.org/vue/b9a2bf2c5b5d39d61026f09b28905239
2.点击手机模型下方的“Open it in a new page”得到独立页面的地址
3.用ios的safari的打开得到的地址
4.在列表页滚动一段距离，然后点击随便一个item跳转到下一页。
5.在下一页返回

期望表现：
应该从bfcache中恢复页面，返回后列表停在原来位置。

实际表现：
列表回到了顶部，页面js重新执行了。如果监听页面的pageshow事件，会发现event.persisted始终是false。

这个bug最早是在vue2.5.16上发现的[点这里](https://github.com/vuejs/vue/issues/8109)
因为vue2.4.4以后优先用MessageChannel的实现nextTick导致了这个bug，所以在一个标准的vue工程里把vue版本降回2.4.3就没有问题了。
但是！在weex的工程里，就算我把vue版本降回2.4.3，还是不行，最终发现可能是下面这一行的问题
https://github.com/weexteam/weex-vue-render/blob/5a8218089deebed99b6e1808e5a7a058a18b2373/src/weex/index.js#L28

core-js这个库也用到了MessageChannel了来实现task

（飞猪的线上产品也是有这个问题的：https://m.fliggy.com/?_projVer=0.1.128）

**Comment by MrRaindrop** [comment]
确实这行 polyfill 会导致这个问题. 不过只是去掉这行，还是会触发此 bug，目前初步把范围缩小在 scrollable 组件的实现上.

**Comment by MrRaindrop** [comment]
@wen911119 我这边发现可能是老版本的 webpack-dev-middleware 的问题，我用 vue-cli 建立的新仓库，用新版本的 dev-server 跑就没有任何问题，于是我尝试 build 出 prod 环境的 bundle，并在 http-server 里面跑，发现在 Vue2.4.3 里并没有这个问题，即使我的代码里包含了这行 polyfill. 目前至少结论是，不会因为 import 了这行 promise polyfill 就导致 bf-cache 出现问题. 不知道你这边是否和我一样是由于 hot reload 的 server 导致，你可能还需要进一步看下.
