### ISSUE TITLE
weex的setViewPort在web端不生效

### ISSUE THREAD

**Issue by figo-fe** [weexteam/weex-vue-render#19]
尝试了使用：
1. weex中 `meta.setViewport({width:1080})`
2. web/index.html 中加入 `<meta name="weex-viewport" content="1080">`

**均无法达到预期**

查看weex-vue-render源码后发现：
1. font-size的计算直接使用屏幕宽度/10，并未使用其他值
2. 设置weex-viewport后的值，并未用于计算scale，其中有一些代码注释掉了

目前临时解决方案：
**修改font-size的计算方式改为：屏幕宽 / 10 * 750 / 1080**

希望官方修复，毕竟各个公司UI的宽度不一定是750

**Comment by MrRaindrop** [comment]
因为当前 1.x 版本所有对 px 的处理放到了编译期（或者编译 + 运行时处理），在 postcss-plugin-px2rem 以及 weex-vue-precompiler 里处理 px2rem 的设计基准 width 值。

不过通过 root font-size 兼容 0.12.x 这种 'weex-viewport' meta 标签的用法以及支持 meta 的动态修改也是可行的。感谢反馈。

- 支持 weex-viewport: https://github.com/weexteam/weex-vue-render/commit/12d78e107feefe6d3fcf2f955b7b8b3ffc158127
- 支持 meta.setViewport: https://github.com/weexteam/weex-vue-render/commit/bb6c5175582b02266c809cae970eb39a66ea8b48

**Comment by figo-fe** [comment]
感谢回复！
另外发现weexSDK 0.18.7-beta-1版本 使用meta模块设置viewport后APP并未生效
目前我们已经在android设置，可能此问题不该在此repo下反馈，
但如果可以，希望同步到weexsdk方。

也希望sdk可以在近期release一版，webview的js通信对我们很有用，但beta版又存在一些问题，暂时无法使用。

**Comment by figo-fe** [comment]
针对此问题的修改又引发了一些启发问题：
目前的方案是：fontSize针对非750满屏宽度，根据比例做了修正，但rem的计算仍然以750（width/75 rem）来算，但发现有些计算却是以1080计算的，比如styleObject2rem传入的rootValue是weex.config.env.rootValue，而_px2rem传入的是75。
望修正，谢谢！

**Comment by erha19** [comment]
@figo-fe If you are using the official template, you can add config `viewport` on the config file here: https://github.com/weex-templates/webpack/blob/master/template/configs/webpack.common.conf.js#L102, add like the example here: http://weex.apache.org/references/modules/meta.html#example.

**Comment by figo-fe** [comment]
@erha19 非常感谢您的解答！
但目前的情况，不是加在哪的问题，这个已经搞定。
问题是weex-vue-render存在bug，修改viewport后显示异常

**Comment by MrRaindrop** [comment]
@figo-fe https://github.com/weexteam/weex-vue-render/releases/tag/v1.0.26 fixe了 `animation.transition` 的问题.
