### ISSUE TITLE
 <input>不能使用v-model来双向绑定了, <cell>不能用了

### ISSUE THREAD

**Issue by cqx0510** [weexteam/weex-vue-render#2]
1) 
`<input v-model="fieldName" />`
双向绑定不起作用

2)
`<list><cell><text>cell不能用了</text></cell><list>`
看代码是用`<section>`替代`<cell>`
但是`<section>`在APP中是不能显示的

**Comment by MrRaindrop** [comment]
@cqx0510 关于第 2 个问题：你的 web 构建和 native  构建应该是分开的，web 用的 vue-loader 配置和 weex-loader  用的配置应该是分开的，所以构建 native bundle 时不应该经过 weex-vue-precompiler 处理. 如果你 APP 里的 `<cell>`  被转成了 `<section>` 你需要检查一下你的构建配置.
