### ISSUE TITLE
weex-vue-render@1.x：PC Chrome 下无法显示小于 12px 的字体

### ISSUE THREAD

**Issue by rccoder** [weexteam/weex-vue-render#8]
`.26667rem` 换算成 px 是 `10px`，但在 PC Chrome 下实际字体大小依旧是 12px（设置里最小字体已经设置为 `6px` 了）

**Comment by MrRaindrop** [comment]
去掉 style/reset.css 里的:

```css
font: initial;
font-size: initial;
```

就可以随意调整大小了. 虽然 initial 是为了防止自动继承，和 weex 保持一致行为，但是通过 font-size 覆盖了样式以后仍然有此问题，另外 font-size 大于默认 medium size (12px) 时没有任何问题，只有小于 medium 才会有此问题.

解决：由于从样式来看，web 端的支持度是 weex 其他端的一个超集，很难通过某些 reset 样式达到所有行为和 weex 保持完全一致，而 `font-size` 的继承行为在 Weex 的实际开发中很少会被开发者碰到，一般都是直接设置在 `<text>` 组件上面，所以 render 后续会将 font, font-size 这两个 reset 样式去掉.

**Comment by rccoder** [comment]
@MrRaindrop  什么时候 npm 会发新版呢

**Comment by MrRaindrop** [comment]
@rccoder 一般有紧急修复或者重要更新时会发布新版本。目前这个不影响正常线上使用，所以这个 fix 等下次发版本的时候一并发布吧.

**Comment by rccoder** [comment]
@MrRaindrop  OK。非常感谢

**Comment by MrRaindrop** [comment]
去掉 `initial` 样式设置会导致组件里 inline 的元素的 font-size 和 line-height 受父元素影响，导致页面渲染局部异常。所以这个样式的删除我们可能要重新考虑下，毕竟 PC Chrome 下的 12px 样式限制不会影响移动设备.

**Comment by MrRaindrop** [comment]
https://github.com/weexteam/weex-vue-render/releases/tag/v1.0.20 fixes that indicator's default line-height is incorrect due to this change of font-size and font.
