### ISSUE TITLE
weex-vue-render@1.x：PC 下用 methods 计算的 fontSize 不对

### ISSUE THREAD

**Issue by rccoder** [weexteam/weex-vue-render#9]
```
<cell>
  <text :style="testStyleMthod()">测试测试</text>
</cell>
```

```
methods: {
  testStyleMthod() {
    return { fontSize: '30px'}
  }
}
```
会直接写 `30px` 在 CSS 里面，而不是转化为 `rem`

**Comment by hacke2** [comment]
methods: {
  testStyleMthod() {
    return { fontSize: 30}
  }
}

这样写试试

**Comment by rccoder** [comment]
@hacke2  这样是好使的，但 0.x 版本可以加 `px`，有一定的升级成本

**Comment by MrRaindrop** [comment]
@rccoder 'px' 还是要加的，不加就有问题了。。至于 PC 下，目前 render 没有适配 PC，只适配了移动端. 这里的问题倒不是 PC 或者单位的问题，主要是 weex-vue-compiler 在解析绑定的时候没有解析函数调用的形式，你把 testStyleMethod 换成 computed 就好了：

```html
<template>
  <div>
    <text :style="testStyleMthod">测试测试</text>
  </div>  
</template>

<script>
  export default {
    computed: {
      testStyleMthod () {
        return { fontSize: '30px'}
      }
    }
  }
</script>
```

http://dotwe.org/vue/e73c12d38257b4cb720a6d6e4a9f9127

不过这也算是一个 weex-vue-compiler 的一个 bug，这边后续会修复这个问题.

**Comment by MrRaindrop** [comment]
手抖 close 掉了... 如果上述回答没有解决你的疑问，可以 reopen 继续讨论.

**Comment by rccoder** [comment]
@MrRaindrop  嗯，`computed` 的话有一些场景可能写起来没 `methods` 方便，比如：
``` js
 <template>
  <div>
    <text  v-for="(item, index) in [1, 1, 2]" :key="index" :style="testStyleMthod(index)">测试测试</text>
  </div>  
</template>

<script>
  export default {
    methods: {
      testStyleMthod (index) {
        if (index === 0) return { fontSize: '28px' }
        return { fontSize: '30px'}
      }
    }
  }
</script>
```

**Comment by Froguard** [comment]
问下这个后续还有计划支持么？
因为一来对于已经写成这样的工程，全量去改，其实不太现实。
二来正如  @rccoder  所说的
>  “computed 的话有一些场景可能写起来没 methods 方便”这个是真的
